package org.progress.crm.util;

import java.io.FileOutputStream;
import java.util.Date;

import com.itextpdf.text.BadElementException;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chapter;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Section;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.List;
import org.progress.crm.logic.Apartaments;

public class PDF {

    private static String FILE = "/tmp/report.pdf";
    private static BaseFont times;
    private static Font times14;

    public static File GeneratePrice(List aparts) {
        try {
            Document document = prepareGen();
            addMetaData(document);
            addPricePage(document, aparts);
//            addContent(document);
            return finalyGen(document);
        } catch (DocumentException | IOException e) {
            e.printStackTrace();
            return null;
        }
    }

    public static File GenerateApartamentsPage(Apartaments apart) {
        try {
            Document document = prepareGen();
            addMetaData(document);
//            addPricePage(document);

//            addContent(document);
            return finalyGen(document);
        } catch (DocumentException | IOException e) {
            e.printStackTrace();
            return null;
        }
    }

    // iText allows to add metadata to the PDF which can be viewed in your Adobe
    // Reader
    // under File -> Properties
    private static void addMetaData(Document document) {
        document.addTitle("My первый PDF");
        document.addSubject("Using iText");
        document.addKeywords("Java, PDF, iText");
        document.addAuthor("Lars Vogel");
        document.addCreator("Lars Vogel");
    }

    private static void addPricePage(Document document, List<Apartaments> aparts)
            throws DocumentException, BadElementException, IOException {
        Paragraph subPara = new Paragraph();
        Chapter mainChapter = new Chapter(subPara, 1);

        // Will create: Report generated by: _name, _date
        mainChapter.add(new Paragraph("Report generated by: " + System.getProperty("user.name") + ", " + new Date(), //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
                new Font(times, 12)));

        Section subCatPart = mainChapter.addSection(subPara);

        // Add a table
        createTable(subCatPart, aparts);

//        // Now add all this to the document
        document.add(mainChapter);

        // Start a new page
//        document.newPage();
    }

    private static void createTable(Section subCatPart, List<Apartaments> aparts)
            throws BadElementException, DocumentException, IOException {
        PdfPTable table = new PdfPTable(6);//3

//        table.setBorderColor(BaseColor.GRAY);
//        table.setPadding(4);
//        table.setSpacing(4);
//        table.setBorderWidth(1);
        PdfPCell c1 = new PdfPCell(new Phrase("Город", new Font(times, 14)));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        c1.setBorderColor(BaseColor.GRAY);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Улица", new Font(times, 14)));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        c1.setBorderColor(BaseColor.GRAY);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Номер дома", new Font(times, 14)));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Описание", new Font(times, 14)));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);
        table.setHeaderRows(1);

        c1 = new PdfPCell(new Phrase("Цена", new Font(times, 14)));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);
        table.setHeaderRows(1);

        c1 = new PdfPCell(new Phrase("Телефон клиента", new Font(times, 14)));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);
        table.setHeaderRows(1);

        for (int i = 0; i < aparts.size(); i++) {
            table.addCell(aparts.get(i).getCityName());
            table.addCell(aparts.get(i).getStreetName());
            table.addCell(aparts.get(i).getHouseNumber());
            table.addCell(aparts.get(i).getDescription());
            table.addCell(String.valueOf(aparts.get(i).getPrice()));
            table.addCell(aparts.get(i).getClientPhone());
        }

        Paragraph p = new Paragraph("asdasdasdтекст текст текст", new Font(times, 14));

        subCatPart.add(table);
        subCatPart.add(p);
    }

    private static Document prepareGen() throws FileNotFoundException, IOException, DocumentException {
        times = BaseFont.createFont("/var/progresscrm/tahoma.ttf", "cp1251", BaseFont.EMBEDDED);
        times14 = new Font(times, 14);
        Document document = new Document(PageSize.LETTER.rotate());//Page landscape orientation
        PdfWriter.getInstance(document, new FileOutputStream(FILE));
        document.open();
        return document;
    }

    private static File finalyGen(Document document) {
        document.close();
        File output = new File(FILE);
        return output;
    }
}
